# Generated by Django 3.1.7 on 2021-02-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed viverra tellus in hac. Magna ac placerat vestibulum lectus mauris. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nunc eget lorem dolor sed viverra ipsum nunc. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Justo nec ultrices dui sapien eget mi proin sed. Enim eu turpis egestas pretium aenean pharetra magna. Amet consectetur adipiscing elit ut aliquam. Diam ut venenatis tellus in metus vulputate eu.'),
            preserve_default=False,
        ),
    ]
