# Generated by Django 3.1.7 on 2021-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'Received'), ('P', 'Processed'), ('D', 'Delivered')], default='R', max_length=1),
        ),
    ]
